"""Atualização 2

Revision ID: 0befbe027e93
Revises: c2bce1fc00d5
Create Date: 2025-11-07 09:18:20.277839

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0befbe027e93'
down_revision: Union[str, Sequence[str], None] = 'c2bce1fc00d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cadastros', 'indicador_ie',
               existing_type=postgresql.ENUM('0', '1', '2', '9', name='cadastroindicadorieenum'),
               type_=sa.Enum('0', '1', '2', '9', name='cadastroindicadorieenum', native_enum=False),
               existing_nullable=False,
               existing_server_default=sa.text("'9'::cadastroindicadorieenum"))
    op.alter_column('contas', 'data_emissao',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.Date(),
               existing_nullable=True)
    op.alter_column('contas', 'data_vencimento',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.Date(),
               existing_nullable=True)
    op.alter_column('contas', 'data_baixa',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.Date(),
               existing_nullable=True)
    op.alter_column('pedidos', 'data_emissao',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.Date(),
               existing_nullable=True)
    op.alter_column('pedidos', 'data_validade',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.Date(),
               existing_nullable=True)
    op.alter_column('pedidos', 'data_finalizacao',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.Date(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pedidos', 'data_finalizacao',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('pedidos', 'data_validade',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('pedidos', 'data_emissao',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('contas', 'data_baixa',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('contas', 'data_vencimento',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('contas', 'data_emissao',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('cadastros', 'indicador_ie',
               existing_type=sa.Enum('0', '1', '2', '9', name='cadastroindicadorieenum', native_enum=False),
               type_=postgresql.ENUM('0', '1', '2', '9', name='cadastroindicadorieenum'),
               existing_nullable=False,
               existing_server_default=sa.text("'9'::cadastroindicadorieenum"))
    # ### end Alembic commands ###
