"""Refatoração completa para arquitetura ERP de 9 modelos

Revision ID: 39e6e0702a6c
Revises: aabee9fc5a5a
Create Date: 2025-11-05 00:36:49.016107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '39e6e0702a6c'
down_revision: Union[str, Sequence[str], None] = 'aabee9fc5a5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empresas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cnpj', sa.String(length=18), nullable=False),
    sa.Column('razao', sa.String(), nullable=False),
    sa.Column('fantasia', sa.String(), nullable=True),
    sa.Column('inscricao_estadual', sa.String(), nullable=True),
    sa.Column('cep', sa.String(length=9), nullable=False),
    sa.Column('estado', sa.String(length=2), nullable=True),
    sa.Column('cidade', sa.String(), nullable=True),
    sa.Column('bairro', sa.String(), nullable=True),
    sa.Column('logradouro', sa.String(), nullable=True),
    sa.Column('numero', sa.String(), nullable=True),
    sa.Column('complemento', sa.String(), nullable=True),
    sa.Column('cnae', sa.String(), nullable=True),
    sa.Column('crt', sa.Enum('simples_nacional', 'lucro_presumido', 'lucro_real', name='empresacrtenum'), nullable=False),
    sa.Column('emissao', sa.Enum('desenvolvimento', 'producao', name='empresaemissaoenum'), nullable=False),
    sa.Column('situacao', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_empresas_cnpj'), 'empresas', ['cnpj'], unique=True)
    op.create_index(op.f('ix_empresas_id'), 'empresas', ['id'], unique=False)
    op.create_table('cadastros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cpf_cnpj', sa.String(length=18), nullable=False),
    sa.Column('nome_razao', sa.String(), nullable=False),
    sa.Column('fantasia', sa.String(), nullable=True),
    sa.Column('tipo_pessoa', sa.Enum('fisica', 'juridica', name='cadastrotipopessoaenum'), nullable=False),
    sa.Column('tipo_cadastro', sa.Enum('cliente', 'fornecedor', 'transportadora', 'vendedor', name='cadastrotipocadastroenum'), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('telefone', sa.String(), nullable=True),
    sa.Column('celular', sa.String(), nullable=True),
    sa.Column('indicador_ie', sa.Boolean(), nullable=True),
    sa.Column('inscricao_estadual', sa.String(), nullable=True),
    sa.Column('cep', sa.String(length=9), nullable=True),
    sa.Column('estado', sa.String(length=2), nullable=True),
    sa.Column('cidade', sa.String(), nullable=True),
    sa.Column('bairro', sa.String(), nullable=True),
    sa.Column('logradouro', sa.String(), nullable=True),
    sa.Column('numero', sa.String(), nullable=True),
    sa.Column('complemento', sa.String(), nullable=True),
    sa.Column('situacao', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id_empresa', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_empresa'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cadastros_cpf_cnpj'), 'cadastros', ['cpf_cnpj'], unique=True)
    op.create_index(op.f('ix_cadastros_email'), 'cadastros', ['email'], unique=False)
    op.create_index(op.f('ix_cadastros_id'), 'cadastros', ['id'], unique=False)
    op.create_index(op.f('ix_cadastros_nome_razao'), 'cadastros', ['nome_razao'], unique=False)
    op.create_table('embalagens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(), nullable=False),
    sa.Column('regras', sa.JSON(), nullable=True),
    sa.Column('situacao', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id_empresa', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_empresa'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_embalagens_id'), 'embalagens', ['id'], unique=False)
    op.create_table('regras_tributarias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(), nullable=True),
    sa.Column('regime_emitente', sa.Enum('simples_nacional', 'lucro_presumido', 'lucro_real', name='regraregimeemitenteenum'), nullable=True),
    sa.Column('tipo_operacao', sa.Enum('venda', 'devolucao', 'remessa', name='regratipooperacaoenum'), nullable=True),
    sa.Column('tipo_cliente', sa.Enum('pf', 'pj_contribuinte', 'pj_isento', 'pj_nao_contribuinte', name='regratipoclienteenum'), nullable=True),
    sa.Column('localizacao_destino', sa.Enum('interna', 'interestadual', 'exterior', name='regralocalizacaodestinoenum'), nullable=True),
    sa.Column('origem_produto', sa.String(), nullable=True),
    sa.Column('ncm_chave', sa.String(), nullable=True),
    sa.Column('prioridade', sa.Integer(), nullable=True),
    sa.Column('situacao', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id_empresa', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_empresa'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_regras_tributarias_id'), 'regras_tributarias', ['id'], unique=False)
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('senha', sa.String(), nullable=False),
    sa.Column('perfil', sa.Enum('admin', 'vendedor', 'financeiro', 'estoquista', name='usuarioperfilenum'), nullable=False),
    sa.Column('situacao', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id_empresa', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_empresa'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.create_table('contas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo_conta', sa.Enum('a_receber', 'a_pagar', name='contatipoenum'), nullable=False),
    sa.Column('situacao', sa.Enum('em_aberto', 'pago', 'vencido', 'cancelado', name='contasituacaoenum'), nullable=False),
    sa.Column('descricao', sa.String(), nullable=True),
    sa.Column('numero_conta', sa.Integer(), nullable=True),
    sa.Column('data_emissao', sa.DateTime(timezone=True), nullable=True),
    sa.Column('data_vencimento', sa.DateTime(timezone=True), nullable=True),
    sa.Column('data_baixa', sa.DateTime(timezone=True), nullable=True),
    sa.Column('plano_contas', sa.Enum('receitas', 'despesas', 'custos', name='contaplanocontasenum'), nullable=True),
    sa.Column('caixa_destino_origem', sa.Enum('sicredi', 'caixa_interno', 'nubank', name='contacaixaenum'), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('pagamento', sa.String(), nullable=True),
    sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id_empresa', sa.Integer(), nullable=False),
    sa.Column('id_fornecedor', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_empresa'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['id_fornecedor'], ['cadastros.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contas_id'), 'contas', ['id'], unique=False)
    op.create_table('pedidos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_emissao', sa.DateTime(timezone=True), nullable=True),
    sa.Column('data_validade', sa.DateTime(timezone=True), nullable=True),
    sa.Column('data_finalizacao', sa.DateTime(timezone=True), nullable=True),
    sa.Column('origem_venda', sa.String(), nullable=True),
    sa.Column('modalidade_frete', sa.String(), nullable=True),
    sa.Column('valor_frete', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('prazo_entrega', sa.String(), nullable=True),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('desconto', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_desconto', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('itens', sa.JSON(), nullable=True),
    sa.Column('pagamento', sa.String(), nullable=True),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('ordem_finalizacao', sa.String(), nullable=True),
    sa.Column('endereco_expedicao', sa.String(), nullable=True),
    sa.Column('natureza_operacao', sa.String(), nullable=True),
    sa.Column('cfop', sa.String(), nullable=True),
    sa.Column('icms_cst', sa.String(), nullable=True),
    sa.Column('icms_aliquota', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('icms_reducao_bc_perc', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('icms_st_cst', sa.String(), nullable=True),
    sa.Column('icms_st_mva_perc', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('icms_st_aliquota', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('ipi_cst', sa.String(), nullable=True),
    sa.Column('ipi_aliquota', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('pis_cst', sa.String(), nullable=True),
    sa.Column('pis_aliquota', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('cofins_cst', sa.String(), nullable=True),
    sa.Column('cofins_aliquota', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('situacao', sa.Enum('disponivel', 'em_aprovacao', 'faturado', 'cancelado', name='pedidosituacaoenum'), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id_empresa', sa.Integer(), nullable=False),
    sa.Column('id_cliente', sa.Integer(), nullable=True),
    sa.Column('id_vendedor', sa.Integer(), nullable=True),
    sa.Column('id_transportadora', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_cliente'], ['cadastros.id'], ),
    sa.ForeignKeyConstraint(['id_empresa'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['id_transportadora'], ['cadastros.id'], ),
    sa.ForeignKeyConstraint(['id_vendedor'], ['cadastros.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pedidos_id'), 'pedidos', ['id'], unique=False)
    op.create_table('produtos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(), nullable=False),
    sa.Column('gtin', sa.String(), nullable=True),
    sa.Column('descricao', sa.String(), nullable=False),
    sa.Column('unidade', sa.Enum('un', 'pc', 'kg', 'mt', 'cx', name='produtounidadeenum'), nullable=True),
    sa.Column('tipo_produto', sa.Enum('mercadoria_revenda', 'materia_prima', 'produto_acabado', 'servico', name='produtotipoenum'), nullable=True),
    sa.Column('grupo', sa.String(), nullable=True),
    sa.Column('subgrupo1', sa.String(), nullable=True),
    sa.Column('subgrupo2', sa.String(), nullable=True),
    sa.Column('subgrupo3', sa.String(), nullable=True),
    sa.Column('subgrupo4', sa.String(), nullable=True),
    sa.Column('subgrupo5', sa.String(), nullable=True),
    sa.Column('url_imagem', sa.String(), nullable=True),
    sa.Column('classificacao_fiscal', sa.String(), nullable=True),
    sa.Column('origem', sa.Enum('nacional', 'estrangeira_import_direta', 'estrangeira_adq_merc_interno', 'nacional_conteudo_import_40', 'nacional_conteudo_import_70', 'nacional_producao_basica', name='produtoorigemenum'), nullable=True),
    sa.Column('ncm', sa.String(), nullable=True),
    sa.Column('cfop', sa.String(), nullable=True),
    sa.Column('preco', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('custo', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('estoque_negativo', sa.Boolean(), nullable=True),
    sa.Column('peso', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('altura', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('largura', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('comprimento', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('situacao', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id_empresa', sa.Integer(), nullable=False),
    sa.Column('id_embalagem', sa.Integer(), nullable=True),
    sa.Column('id_fornecedor', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_embalagem'], ['embalagens.id'], ),
    sa.ForeignKeyConstraint(['id_empresa'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['id_fornecedor'], ['cadastros.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_produtos_descricao'), 'produtos', ['descricao'], unique=False)
    op.create_index(op.f('ix_produtos_gtin'), 'produtos', ['gtin'], unique=False)
    op.create_index(op.f('ix_produtos_id'), 'produtos', ['id'], unique=False)
    op.create_index(op.f('ix_produtos_sku'), 'produtos', ['sku'], unique=True)
    op.create_table('estoque',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lote', sa.String(), nullable=True),
    sa.Column('deposito', sa.String(), nullable=True),
    sa.Column('rua', sa.String(), nullable=True),
    sa.Column('nivel', sa.String(), nullable=True),
    sa.Column('cor', sa.String(), nullable=True),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('situacao', sa.Enum('disponivel', 'reservado', 'indisponivel', name='estoquesituacaoenum'), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id_empresa', sa.Integer(), nullable=False),
    sa.Column('id_produto', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_empresa'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['id_produto'], ['produtos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_estoque_id'), 'estoque', ['id'], unique=False)
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_full_name'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_customers_email'), table_name='customers')
    op.drop_index(op.f('ix_customers_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_name'), table_name='customers')
    op.drop_table('customers')
    op.drop_index(op.f('ix_businesses_id'), table_name='businesses')
    op.drop_index(op.f('ix_businesses_name'), table_name='businesses')
    op.drop_table('businesses')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('businesses',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('businesses_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='businesses_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_businesses_name'), 'businesses', ['name'], unique=False)
    op.create_index(op.f('ix_businesses_id'), 'businesses', ['id'], unique=False)
    op.create_table('customers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('business_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], name=op.f('customers_business_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('customers_pkey'))
    )
    op.create_index(op.f('ix_customers_name'), 'customers', ['name'], unique=False)
    op.create_index(op.f('ix_customers_id'), 'customers', ['id'], unique=False)
    op.create_index(op.f('ix_customers_email'), 'customers', ['email'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('full_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('business_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('role', postgresql.ENUM('admin', 'comercial', 'user', name='userrole'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], name=op.f('users_business_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('users_pkey'))
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_full_name'), 'users', ['full_name'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_index(op.f('ix_estoque_id'), table_name='estoque')
    op.drop_table('estoque')
    op.drop_index(op.f('ix_produtos_sku'), table_name='produtos')
    op.drop_index(op.f('ix_produtos_id'), table_name='produtos')
    op.drop_index(op.f('ix_produtos_gtin'), table_name='produtos')
    op.drop_index(op.f('ix_produtos_descricao'), table_name='produtos')
    op.drop_table('produtos')
    op.drop_index(op.f('ix_pedidos_id'), table_name='pedidos')
    op.drop_table('pedidos')
    op.drop_index(op.f('ix_contas_id'), table_name='contas')
    op.drop_table('contas')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_regras_tributarias_id'), table_name='regras_tributarias')
    op.drop_table('regras_tributarias')
    op.drop_index(op.f('ix_embalagens_id'), table_name='embalagens')
    op.drop_table('embalagens')
    op.drop_index(op.f('ix_cadastros_nome_razao'), table_name='cadastros')
    op.drop_index(op.f('ix_cadastros_id'), table_name='cadastros')
    op.drop_index(op.f('ix_cadastros_email'), table_name='cadastros')
    op.drop_index(op.f('ix_cadastros_cpf_cnpj'), table_name='cadastros')
    op.drop_table('cadastros')
    op.drop_index(op.f('ix_empresas_id'), table_name='empresas')
    op.drop_index(op.f('ix_empresas_cnpj'), table_name='empresas')
    op.drop_table('empresas')
    # ### end Alembic commands ###
