"""Atualização 3

Revision ID: 5809b558ec78
Revises: 0befbe027e93
Create Date: 2025-11-07 17:22:47.687017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5809b558ec78'
down_revision: Union[str, Sequence[str], None] = '0befbe027e93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cadastros_cpf_cnpj'), table_name='cadastros')
    op.create_index(op.f('ix_cadastros_cpf_cnpj'), 'cadastros', ['cpf_cnpj'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cadastros_cpf_cnpj'), table_name='cadastros')
    op.create_index(op.f('ix_cadastros_cpf_cnpj'), 'cadastros', ['cpf_cnpj'], unique=True)
    # ### end Alembic commands ###
