"""Adiciona tabela Products

Revision ID: aabee9fc5a5a
Revises: 
Create Date: 2025-11-04 13:35:46.005704

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aabee9fc5a5a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. Adiciona a coluna, mas PERMITE nulos temporariamente
    op.add_column('users', sa.Column('role', sa.Enum('admin', 'comercial', 'user', name='userrole'), nullable=True))
    
    # 2. Atualiza todos os usuários existentes para terem a role 'user'
    op.execute("UPDATE users SET role = 'user' WHERE role IS NULL")
    
    # 3. Agora que ninguém é nulo, define a coluna como NOT NULL
    op.alter_column('users', 'role', nullable=False)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
