"""Atualiza PedidoSituacaoEnum

Revision ID: c2bce1fc00d5
Revises: cf3b1c16751c
Create Date: 2025-11-06 14:33:11.680436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c2bce1fc00d5'
down_revision: Union[str, Sequence[str], None] = 'cf3b1c16751c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pedidos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_cliente', sa.Integer(), nullable=True),
    sa.Column('id_vendedor', sa.Integer(), nullable=True),
    sa.Column('id_transportadora', sa.Integer(), nullable=True),
    sa.Column('origem_venda', sa.String(), nullable=True),
    sa.Column('situacao', sa.Enum('orcamento', 'aprovacao', 'programacao', 'producao', 'embalagem', 'faturamento', 'expedicao', 'cancelado', name='pedidosituacaoenum'), nullable=False),
    sa.Column('data_emissao', sa.DateTime(timezone=True), nullable=True),
    sa.Column('data_validade', sa.DateTime(timezone=True), nullable=True),
    sa.Column('data_finalizacao', sa.DateTime(timezone=True), nullable=True),
    sa.Column('prazo_entrega', sa.String(), nullable=True),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('desconto', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_desconto', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('pagamento', sa.String(), nullable=True),
    sa.Column('modalidade_frete', sa.String(), nullable=True),
    sa.Column('valor_frete', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('endereco_expedicao', sa.String(), nullable=True),
    sa.Column('itens', sa.JSON(), nullable=True),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('natureza_operacao', sa.String(), nullable=True),
    sa.Column('cfop', sa.String(), nullable=True),
    sa.Column('icms_cst', sa.String(), nullable=True),
    sa.Column('icms_aliquota', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('icms_reducao_bc_perc', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('icms_st_cst', sa.String(), nullable=True),
    sa.Column('icms_st_mva_perc', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('icms_st_aliquota', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('ipi_cst', sa.String(), nullable=True),
    sa.Column('ipi_aliquota', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('pis_cst', sa.String(), nullable=True),
    sa.Column('pis_aliquota', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('cofins_cst', sa.String(), nullable=True),
    sa.Column('cofins_aliquota', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('ordem_finalizacao', sa.String(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id_empresa', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_cliente'], ['cadastros.id'], ),
    sa.ForeignKeyConstraint(['id_empresa'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['id_transportadora'], ['cadastros.id'], ),
    sa.ForeignKeyConstraint(['id_vendedor'], ['cadastros.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pedidos_id'), 'pedidos', ['id'], unique=False)
    op.alter_column('cadastros', 'indicador_ie',
               existing_type=postgresql.ENUM('0', '1', '2', '9', name='cadastroindicadorieenum'),
               nullable=False,
               existing_server_default=sa.text("'9'::cadastroindicadorieenum"))
    op.alter_column('cadastros', 'cep',
               existing_type=sa.VARCHAR(length=9),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cadastros', 'cep',
               existing_type=sa.VARCHAR(length=9),
               nullable=True)
    op.alter_column('cadastros', 'indicador_ie',
               existing_type=postgresql.ENUM('0', '1', '2', '9', name='cadastroindicadorieenum'),
               nullable=True,
               existing_server_default=sa.text("'9'::cadastroindicadorieenum"))
    op.drop_index(op.f('ix_pedidos_id'), table_name='pedidos')
    op.drop_table('pedidos')
    # ### end Alembic commands ###
